name: Selenium Tests

on:
  push:
    branches:
      - main  # adjust branch name as needed

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Choose your Java version

      - name: Download and Install WebDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run Selenium Tests
        run: |
          mvn test  # Adjust the Maven command based on your project structure and build tool